"""Compare two or more runs of the same configuration.

A p95 within one run says how spiky that run was. It says nothing about whether
the run itself is repeatable, and those are different questions. This answers the
second one by diffing runs that used identical config, which is the only way to
know how much weight a single number can carry.

It matters here: the first two full runs of this suite agreed on read latency to
within about 10% and disagreed on ingest time and saturated throughput by 60-70%.
Without this comparison the suite would have published the load times as though
they were measurements.
"""

import json
from pathlib import Path

from graphbench import paths

# (label, extraction path, absolute floor below which a difference is not real)
#
# The floor matters more than it looks. Kùzu's RETURN 1 moved from 0.04ms to 0.20ms
# between two runs, which is a 338% spread and 0.16ms of absolute difference. A
# percentage on a sub-millisecond measurement is reporting the resolution of a
# Python-timed client call, not the stability of the engine. Flagging that as
# "unstable" alongside CognoDB's 3-hop p95 moving by 10.7 *seconds* would put two
# completely different things in the same bucket.
#
# So a metric is unstable only when the relative spread AND the absolute difference
# both clear their thresholds. Latency floors are 0.5ms, which is roughly where
# client-side timing of a network round trip stops being trustworthy. Rate floors are
# generous because a few hundred rows/second is noise on a five-figure number.
METRICS: list[tuple[str, str, float]] = [
    ("load total (s)", "load.total_seconds", 1.0),
    ("nodes/s", "load.nodes_per_second", 500.0),
    ("rels/s", "load.rels_per_second", 500.0),
    ("RETURN 1 p50", "read.baseline_noop.p50_ms", 0.5),
    ("point p50", "read.point_lookup.p50_ms", 0.5),
    ("1-hop p50", "read.traversal_1hop.p50_ms", 0.5),
    ("2-hop p50", "read.traversal_2hop.p50_ms", 0.5),
    ("3-hop p50", "read.traversal_3hop.p50_ms", 0.5),
    ("3-hop p95", "read.traversal_3hop.p95_ms", 0.5),
    ("group-by p50", "read.aggregation_groupby_cohort.p50_ms", 0.5),
    ("qps @1", "mixed.1.qps", 5.0),
    ("qps @10", "mixed.10.qps", 5.0),
    ("qps @40", "mixed.40.qps", 5.0),
]

# Above this spread, a single run's figure is not a measurement, provided the
# absolute difference also clears the metric's floor.
UNSTABLE_PERCENT = 25.0


def _extract(record: dict, path: str) -> float | None:
    kind, *rest = path.split(".")
    if kind == "load":
        return (record.get("load") or {}).get(rest[0])
    if kind == "read":
        name, field = rest
        workload = next((w for w in record.get("reads", []) if w["name"] == name), None)
        return workload["latency"].get(field) if workload else None
    if kind == "mixed":
        level = int(rest[0])
        for entry in (record.get("mixed") or {}).get("levels", []):
            if entry["concurrency"] == level:
                return entry.get(rest[1])
    return None


def load_runs(run_ids: list[str]) -> dict[str, dict[str, dict]]:
    out: dict[str, dict[str, dict]] = {}
    for run_id in run_ids:
        run_dir = paths.RESULTS_DIR / run_id
        if not (run_dir / "run.json").exists():
            raise FileNotFoundError(f"no run.json in {run_dir}")
        out[run_id] = {
            json.loads(f.read_text())["platform"]["id"]: json.loads(f.read_text())
            for f in sorted(run_dir.glob("*.json"))
            if f.name != "run.json"
        }
    return out


def _spread(values: list[float]) -> float:
    """Spread as a percentage of the smallest value. Two runs is a range, not a
    standard deviation, and pretending otherwise would overstate the rigour."""
    lo, hi = min(values), max(values)
    return 0.0 if lo == 0 else (hi - lo) / lo * 100.0


def build(run_ids: list[str]) -> int:
    runs = load_runs(run_ids)
    platforms = sorted({pid for run in runs.values() for pid in run})

    lines = [
        "# Run-to-run variance",
        "",
        "Generated by `graphbench compare`. Do not edit by hand.",
        "",
        f"Comparing {len(run_ids)} runs of identical configuration: "
        + ", ".join(f"`{r}`" for r in run_ids)
        + ".",
        "",
        "Spread is the range as a percentage of the smaller value, not a standard "
        f"deviation: with {len(run_ids)} runs a range is all the data supports. Abs is "
        "the same difference in the metric's own units.",
        "",
        f"A row is **unstable** when the spread exceeds {UNSTABLE_PERCENT:.0f}% *and* "
        "the absolute difference clears a per-metric floor. Both conditions are needed: "
        "0.04ms against 0.20ms is a 338% spread and 0.16ms of real difference, which is "
        "the resolution of a Python-timed client call rather than engine instability. "
        "Rows that clear the percentage but not the floor say so.",
        "",
        "A single run's figure for an unstable metric is not a measurement and should "
        "not be used to rank engines.",
        "",
    ]

    unstable_metrics: dict[str, int] = {}

    for pid in platforms:
        display = next(
            (runs[r][pid]["platform"]["display"] for r in run_ids if pid in runs[r]), pid
        )
        lines += [f"## {display}", ""]
        header = (
            "| Metric | " + " | ".join(r[-9:] for r in run_ids) + " | Spread | Abs | |"
        )
        lines += [
            header,
            "| --- | " + " | ".join(["---:"] * len(run_ids)) + " | ---: | ---: | --- |",
        ]

        for label, path, floor in METRICS:
            values = []
            cells = []
            for run_id in run_ids:
                record = runs[run_id].get(pid)
                value = _extract(record, path) if record else None
                cells.append("-" if value is None else f"{value:,.2f}")
                if value is not None:
                    values.append(value)
            if len(values) < 2:
                continue
            spread = _spread(values)
            absolute = max(values) - min(values)
            unstable = spread > UNSTABLE_PERCENT and absolute >= floor
            if unstable:
                unstable_metrics[label] = unstable_metrics.get(label, 0) + 1
            note = ""
            if spread > UNSTABLE_PERCENT and not unstable:
                note = f"below the {floor:g} floor"
            elif unstable:
                note = "**unstable**"
            lines.append(
                f"| {label} | " + " | ".join(cells)
                + f" | {spread:+.0f}% | {absolute:,.2f} | {note} |"
            )
        lines.append("")

    lines += ["## Which metrics survive repetition", ""]
    if unstable_metrics:
        lines += [
            "Counting how many platforms showed more than "
            f"{UNSTABLE_PERCENT:.0f}% spread on each metric:",
            "",
            "| Metric | Platforms unstable |",
            "| --- | ---: |",
        ]
        for label, count in sorted(unstable_metrics.items(), key=lambda kv: -kv[1]):
            lines.append(f"| {label} | {count} of {len(platforms)} |")
        lines += [
            "",
            "Read the results table with this in mind. Anything listed here is a "
            "range rather than a value, and a difference between two engines smaller "
            "than the spread on this page is not a finding.",
            "",
        ]
    else:
        lines += ["Every metric repeated within the threshold.", ""]

    out = paths.DOCS_DIR / "VARIANCE.md"
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {paths.display(out)}")
    return 0


def available_runs() -> list[str]:
    return sorted(
        d.name for d in paths.RESULTS_DIR.iterdir() if (d / "run.json").exists()
    )


def resolve(run_ids: list[str] | None) -> list[str]:
    """Default to every completed run, since that is what a variance check wants."""
    if run_ids:
        return run_ids
    found = available_runs()
    if len(found) < 2:
        raise ValueError(
            f"need at least 2 completed runs to compare, found {len(found)}: {found}"
        )
    return found


def latest_path() -> Path:
    return paths.DOCS_DIR / "VARIANCE.md"
