"""Compare two or more runs of the same configuration.

A p95 within one run says how spiky that run was. It says nothing about whether
the run itself is repeatable, and those are different questions. This answers the
second one by diffing runs that used identical config, which is the only way to
know how much weight a single number can carry.

It matters here: the first two full runs of this suite agreed on read latency to
within about 10% and disagreed on ingest time and saturated throughput by 60-70%.
Without this comparison the suite would have published the load times as though
they were measurements.
"""

import json
from pathlib import Path

from graphbench import paths

# (label, how to pull it out of a platform record)
METRICS: list[tuple[str, str]] = [
    ("load total (s)", "load.total_seconds"),
    ("nodes/s", "load.nodes_per_second"),
    ("rels/s", "load.rels_per_second"),
    ("RETURN 1 p50", "read.baseline_noop.p50_ms"),
    ("point p50", "read.point_lookup.p50_ms"),
    ("1-hop p50", "read.traversal_1hop.p50_ms"),
    ("2-hop p50", "read.traversal_2hop.p50_ms"),
    ("3-hop p50", "read.traversal_3hop.p50_ms"),
    ("3-hop p95", "read.traversal_3hop.p95_ms"),
    ("group-by p50", "read.aggregation_groupby_cohort.p50_ms"),
    ("qps @1", "mixed.1.qps"),
    ("qps @10", "mixed.10.qps"),
    ("qps @40", "mixed.40.qps"),
]

# Above this spread, a single run's figure is not a measurement.
UNSTABLE_PERCENT = 25.0


def _extract(record: dict, path: str) -> float | None:
    kind, *rest = path.split(".")
    if kind == "load":
        return (record.get("load") or {}).get(rest[0])
    if kind == "read":
        name, field = rest
        workload = next((w for w in record.get("reads", []) if w["name"] == name), None)
        return workload["latency"].get(field) if workload else None
    if kind == "mixed":
        level = int(rest[0])
        for entry in (record.get("mixed") or {}).get("levels", []):
            if entry["concurrency"] == level:
                return entry.get(rest[1])
    return None


def load_runs(run_ids: list[str]) -> dict[str, dict[str, dict]]:
    out: dict[str, dict[str, dict]] = {}
    for run_id in run_ids:
        run_dir = paths.RESULTS_DIR / run_id
        if not (run_dir / "run.json").exists():
            raise FileNotFoundError(f"no run.json in {run_dir}")
        out[run_id] = {
            json.loads(f.read_text())["platform"]["id"]: json.loads(f.read_text())
            for f in sorted(run_dir.glob("*.json"))
            if f.name != "run.json"
        }
    return out


def _spread(values: list[float]) -> float:
    """Spread as a percentage of the smallest value. Two runs is a range, not a
    standard deviation, and pretending otherwise would overstate the rigour."""
    lo, hi = min(values), max(values)
    return 0.0 if lo == 0 else (hi - lo) / lo * 100.0


def build(run_ids: list[str]) -> int:
    runs = load_runs(run_ids)
    platforms = sorted({pid for run in runs.values() for pid in run})

    lines = [
        "# Run-to-run variance",
        "",
        "Generated by `graphbench compare`. Do not edit by hand.",
        "",
        f"Comparing {len(run_ids)} runs of identical configuration: "
        + ", ".join(f"`{r}`" for r in run_ids)
        + ".",
        "",
        "Spread is the range as a percentage of the smaller value, not a standard "
        f"deviation: with {len(run_ids)} runs a range is all the data supports. Rows "
        f"marked **unstable** vary by more than {UNSTABLE_PERCENT:.0f}%, which means a "
        "single run's figure for that metric is not a measurement and should not be "
        "used to rank engines.",
        "",
    ]

    unstable_metrics: dict[str, int] = {}

    for pid in platforms:
        display = next(
            (runs[r][pid]["platform"]["display"] for r in run_ids if pid in runs[r]), pid
        )
        lines += [f"## {display}", ""]
        header = "| Metric | " + " | ".join(r[-9:] for r in run_ids) + " | Spread | |"
        lines += [header, "| --- | " + " | ".join(["---:"] * len(run_ids)) + " | ---: | --- |"]

        for label, path in METRICS:
            values = []
            cells = []
            for run_id in run_ids:
                record = runs[run_id].get(pid)
                value = _extract(record, path) if record else None
                cells.append("-" if value is None else f"{value:,.2f}")
                if value is not None:
                    values.append(value)
            if len(values) < 2:
                continue
            spread = _spread(values)
            unstable = spread > UNSTABLE_PERCENT
            if unstable:
                unstable_metrics[label] = unstable_metrics.get(label, 0) + 1
            lines.append(
                f"| {label} | " + " | ".join(cells) + f" | {spread:+.0f}% | "
                + ("**unstable**" if unstable else "") + " |"
            )
        lines.append("")

    lines += ["## Which metrics survive repetition", ""]
    if unstable_metrics:
        lines += [
            "Counting how many platforms showed more than "
            f"{UNSTABLE_PERCENT:.0f}% spread on each metric:",
            "",
            "| Metric | Platforms unstable |",
            "| --- | ---: |",
        ]
        for label, count in sorted(unstable_metrics.items(), key=lambda kv: -kv[1]):
            lines.append(f"| {label} | {count} of {len(platforms)} |")
        lines += [
            "",
            "Read the results table with this in mind. Anything listed here is a "
            "range rather than a value, and a difference between two engines smaller "
            "than the spread on this page is not a finding.",
            "",
        ]
    else:
        lines += ["Every metric repeated within the threshold.", ""]

    out = paths.DOCS_DIR / "VARIANCE.md"
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out.relative_to(paths.ROOT)}")
    return 0


def available_runs() -> list[str]:
    return sorted(
        d.name for d in paths.RESULTS_DIR.iterdir() if (d / "run.json").exists()
    )


def resolve(run_ids: list[str] | None) -> list[str]:
    """Default to every completed run, since that is what a variance check wants."""
    if run_ids:
        return run_ids
    found = available_runs()
    if len(found) < 2:
        raise ValueError(
            f"need at least 2 completed runs to compare, found {len(found)}: {found}"
        )
    return found


def latest_path() -> Path:
    return paths.DOCS_DIR / "VARIANCE.md"
